version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels: [dependencies]
    assignees: [sonqyau]
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps(workflows)
    groups:
      github-actions:
        patterns: ["*"]
